repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0       # Black version
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0        # Flake8 version
    hooks:
      - id: flake8
        additional_dependencies: [mccabe, pycodestyle, pyflakes]
