version: '3.9'
services:
  chatbot:
    build: .
    container_name: confluence-rag-chatbot-ollama
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
