FROM python:3.11-slim

WORKDIR /app

COPY requirements-ui.txt .

RUN pip install --no-cache-dir -r requirements-ui.txt

COPY frontend ./frontend

EXPOSE 8501

CMD ["streamlit", "run", "frontend/streamlit-ui.py", "--server.port=8501", "--server.address=0.0.0.0"]