apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-backend
  labels:
    app: confluence-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: confluence-backend
  template:
    metadata:
      labels:
        app: confluence-backend
    spec:
      containers:
        - name: backend
          image: confluence-rag-chatbot-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: confluence-config
            - secretRef:
                name: confluence-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: confluence-backend
spec:
  selector:
    app: confluence-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
