apiVersion: v1
kind: Secret
metadata:
  name: confluence-secrets
type: Opaque
stringData:
  POSTGRES_URL: "postgresql://chatuser:chatpass@postgres:5432/chatdb"
  CONFLUENCE_API_TOKEN: "ATATT3xFfGF0QgpYSYJ49rOYGiRiHDmRkQTW2leDT6J8m05ONRRflq6IrH5K6CHkwgawl8bCtC5iwieS0bHd9nnoPU5DkcmmCXUnDQYwosuWZU5YUcoDoxgARG7d9nrQyls97cKxQQmT0MtIVDnC3hUFAME8zRj6jmr4x9voKs2bKSALO8IFzNQ=8A9EF821"
  OLLAMA_BASE_URL: "http://ollama:11434"
  AZURE_STORAGE_CONNECTION_STRING: ""
